"""ATH OS-SE waveguide generator (single plane-wave driven throat, optional enclosure)."""

from __future__ import annotations

from pathlib import Path
from typing import Callable

from blab.ath import (
    ath_mirror_axes_for_result,
    clean_ath_mesh_output,
    clean_ath_reduced_mesh_output,
    run_ath,
    write_ath_gmsh_path,
    write_ath_output_root,
)
from blab.protocol import radiator_to_dict
from generators import mesh_stats, quality_warning_text

REPO_ROOT = Path(__file__).resolve().parents[3]
ATH_EXE = REPO_ROOT / "ath" / "ath.exe"
GMSH_EXE = REPO_ROOT / "gmsh" / "gmsh-4.15.2-Windows64" / "gmsh.exe"

SCHEMA = {
    "id": "ath_waveguide",
    "title": "ATH OS-SE Waveguide",
    "description": (
        "OS-SE waveguide/horn generated by Ath (ath.exe): plane-wave compression-driver throat, "
        "superformula mouth morphed to a rounded rectangle, optional rollback enclosure. "
        "Device fires along +z; mesh units are mm. Set raw_cfg to bypass the template with a full ATH config."
    ),
    "params": {
        "type": "object",
        "properties": {
            "throat_diameter": {
                "type": "number",
                "default": 25.4,
                "minimum": 10,
                "maximum": 80,
                "description": "Throat (compression driver exit) diameter in mm.",
            },
            "throat_angle": {
                "type": "number",
                "default": 0,
                "minimum": 0,
                "maximum": 30,
                "description": "Conic-section launch angle at the throat in degrees.",
            },
            "length": {
                "type": "number",
                "default": 90,
                "minimum": 20,
                "maximum": 400,
                "description": "Waveguide axial depth in mm.",
            },
            "mouth_width": {
                "type": "number",
                "default": 220,
                "minimum": 60,
                "maximum": 600,
                "description": "Morph target mouth width in mm.",
            },
            "mouth_height": {
                "type": "number",
                "default": 160,
                "minimum": 60,
                "maximum": 600,
                "description": "Morph target mouth height in mm.",
            },
            "corner_radius": {
                "type": "number",
                "default": 20,
                "minimum": 0,
                "maximum": 100,
                "description": "Mouth rounded-rectangle corner radius in mm.",
            },
            "term_s": {
                "type": "number",
                "default": 0.8,
                "minimum": 0.1,
                "maximum": 1.5,
                "description": "OS-SE termination shape parameter Term.s (dimensionless).",
            },
            "term_q": {
                "type": "number",
                "default": 0.996,
                "minimum": 0.5,
                "maximum": 1.0,
                "description": "OS-SE termination parameter Term.q (dimensionless).",
            },
            "term_n": {
                "type": "number",
                "default": 4,
                "minimum": 1,
                "maximum": 10,
                "description": "OS-SE termination superellipse order Term.n (dimensionless).",
            },
            "os_k": {
                "type": "number",
                "default": 1.0,
                "minimum": 0.1,
                "maximum": 10,
                "description": "OS.k oblate-spheroid flare constant (dimensionless).",
            },
            "angular_segments": {
                "type": "integer",
                "default": 48,
                "minimum": 16,
                "maximum": 160,
                "description": "Mesh.AngularSegments around the waveguide circumference.",
            },
            "length_segments": {
                "type": "integer",
                "default": 10,
                "minimum": 4,
                "maximum": 40,
                "description": "Mesh.LengthSegments along the waveguide axis.",
            },
            "throat_resolution": {
                "type": "number",
                "default": 4,
                "minimum": 1,
                "maximum": 20,
                "description": "Mesh element size at the throat in mm.",
            },
            "mouth_resolution": {
                "type": "number",
                "default": 20,
                "minimum": 4,
                "maximum": 60,
                "description": "Mesh element size at the mouth in mm.",
            },
            "quadrants": {
                "type": "integer",
                "default": 1,
                "description": (
                    "Mesh.Quadrants: 1 generates one quadrant (Ath reports Sym=xy; the cleaner mirrors it "
                    "to the full mesh), 14 generates a half mesh (Sym=x)."
                ),
            },
            "enclosure": {
                "type": "boolean",
                "default": True,
                "description": (
                    "True: free-standing rollback enclosure behind the waveguide (ABEC.SimType 2). "
                    "False: infinite-baffle style waveguide only (ABEC.SimType 1)."
                ),
            },
            "enclosure_depth": {
                "type": "number",
                "default": 160,
                "minimum": 30,
                "maximum": 600,
                "description": "Enclosure depth in mm. Ath quirk: MUST exceed length or the back box is silently omitted.",
            },
            "enclosure_edge_radius": {
                "type": "number",
                "default": 15,
                "minimum": 1,
                "maximum": 60,
                "description": "Enclosure edge roundover radius in mm.",
            },
            "raw_cfg": {
                "type": "string",
                "description": "Full ATH config text. If set, every other parameter is ignored and this text is passed to ath.exe verbatim.",
            },
        },
    },
}


def _build_cfg(p: dict) -> str:
    enclosure = bool(p["enclosure"])
    depth = max(float(p["enclosure_depth"]), float(p["length"]) + 10.0)  # Ath: Depth must be > Length
    lines = [
        "; generated by blabctl ath_waveguide",
        "Throat.Profile = 1 ; OS-SE",
        f"Throat.Diameter = {p['throat_diameter']:g} ; [mm]",
        f"Throat.Angle = {p['throat_angle']:g} ; [deg]",
        f"Length = {p['length']:g} ; [mm]",
        f"Term.s = {p['term_s']:g}",
        f"Term.q = {p['term_q']:g}",
        f"Term.n = {p['term_n']:g}",
        f"OS.k = {p['os_k']:g}",
        "Slot.Length = 0",
        "",
        "GCurve.Type = 2 ; superformula",
        f"GCurve.Width = {min(float(p['mouth_width']), float(p['mouth_height'])) * 0.25:g} ; [mm]",
        "GCurve.Dist = 0.5",
        "GCurve.SF = 1,1.2,4,1.5,14,2.5 ; {a, b, m, n1, n2, n3}",
        "GCurve.Rot = 0",
        "GCurve.AspectRatio = 1",
        "",
        f"Morph.TargetWidth = {p['mouth_width']:g} ; [mm]",
        f"Morph.TargetHeight = {p['mouth_height']:g} ; [mm]",
        "Morph.TargetShape = 1 ; rounded rectangle (2 would morph to a circle)",
        "Morph.FixedPart = 0",
        "Morph.Rate = 3",
        f"Morph.CornerRadius = {p['corner_radius']:g} ; [mm]",
        "Morph.AllowShrinkage = 1",
        "",
        f"Mesh.AngularSegments = {int(p['angular_segments'])}",
        f"Mesh.LengthSegments = {int(p['length_segments'])}",
        "Mesh.CornerSegments = 4",
        f"Mesh.ThroatResolution = {p['throat_resolution']:g} ; [mm]",
        f"Mesh.MouthResolution = {p['mouth_resolution']:g} ; [mm]",
        f"Mesh.Quadrants = {int(p['quadrants'])}",
        "Mesh.SubdomainSlices =",
        "",
    ]
    if enclosure:
        lines += [
            "Mesh.Enclosure = {",
            " Spacing = 15,15,15,15 ; left,top,right,bottom [mm]",
            f" Depth = {depth:g} ; [mm] must be > Length or Ath silently drops the back box",
            f" EdgeRadius = {p['enclosure_edge_radius']:g} ; [mm]",
            " EdgeType = 1 ; rounded",
            " FrontResolution = 20,20,20,20",
            " BackResolution = 40,40,40,40",
            "}",
            "",
        ]
    lines += [
        "Output.STL = 1",
        f"ABEC.SimType = {2 if enclosure else 1} ; 2 = free standing with enclosure, 1 = infinite baffle",
        "",
    ]
    return "\n".join(lines)


def generate(params: dict, out_dir: Path, name: str, emit: Callable[[dict], None]) -> dict:
    raw_cfg = params.get("raw_cfg")
    config_text = str(raw_cfg) if raw_cfg else _build_cfg(params)

    ath_cfg = ATH_EXE.parent / "ath.cfg"
    write_ath_output_root(ath_cfg, out_dir)
    write_ath_gmsh_path(ath_cfg, GMSH_EXE)

    emit({"event": "progress", "stage": "ath", "message": f"Running ath.exe ({name})"})
    result = run_ath(ath_exe=ATH_EXE, config_text=config_text, run_root=out_dir, case_name=name, timeout_s=180.0)

    emit({"event": "progress", "stage": "clean", "message": "Cleaning Ath mesh output"})
    # Which planes Ath mirrored the reduced mesh across (from its solving file):
    # quadrants=1 -> ("x","y"), quadrants=14 -> ("x",). Persisted in the result
    # so cmd_solve can refuse a symmetry setting the reduced mesh was not built for.
    mirror_axes = ath_mirror_axes_for_result(result)
    result = clean_ath_mesh_output(result, mirror_axes=mirror_axes)
    result = clean_ath_reduced_mesh_output(result)

    triangles, bbox_mm = mesh_stats(result.cleaned_msh_path)
    stl_matches = sorted(result.output_dir.rglob("*.stl"))
    return {
        "mesh_path": str(result.msh_path),
        "cleaned_msh_path": str(result.cleaned_msh_path),
        "reduced_msh_path": str(result.reduced_cleaned_msh_path),
        "mirror_axes": list(mirror_axes),
        "stl_path": str(stl_matches[0]) if stl_matches else None,
        "triangles": triangles,
        "bbox_mm": bbox_mm,
        "driven_tag": result.driven_tag,
        "radiators": [radiator_to_dict(radiator) for radiator in result.radiators],
        "quality_warning": quality_warning_text(result.quality_warning),
        "config_used": str(result.config_path),
    }
